sudo: required
services:
  - docker
    
before_install:
  - docker build -t imantaba/docker-react -f Dockerfile.dev .

# scripts that should be run for our test 
script:
  - docker run imantaba/docker-react npm run test -- --coverage
